services:
  - type: web
    name: sanskrit-translator
    env: node
    region: oregon
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: NPM_CONFIG_PRODUCTION
        value: false
      # OPENAI_API_KEY must be set in Render dashboard
    autoDeploy: true
    domains:
      - translatorassistant.com
      - www.translatorassistant.com